# Custom Layers

Layers without Parameters

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.9581e-09, grad_fn=<MeanBackward0>)

Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.2503,  1.8359, -1.1828],
        [ 0.0249,  0.6579, -1.1666],
        [ 0.4929,  0.1950,  0.8016],
        [-0.2307, -0.0842, -1.0550],
        [ 1.0177, -0.4363,  1.1997]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [7]:
dense(torch.rand(2, 5))

tensor([[0.0101, 1.3086, 0.0000],
        [0.4401, 0.8658, 0.0000]])

Construct models using custom layers

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])